version: '3.8'

services:
  pygeoapi:
    image: geopython/pygeoapi
    ports:
      - "5000:80"
    volumes:
      - ./pygeoapi-config.yml:/pygeoapi/local.config.yml
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgis/postgis
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d my_geospatial_db"]
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /var/lib/postgresql/data
      - ./scripts/init_postgis_test.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"